title: Civic Technology
description: >
  How to build things that matter.
baseurl: "/civictechcourse"
url: "https://github.com/siawyoung/immaculate"
paginate:	2 # The number of posts to show per page on your homepage
name: "Abhi Nemani"
email: abhinemani@uchicago.edu
markdown: kramdown
permalink: none
kramdown:
  parse_block_html: true
plugins:
  - jekyll-paginate
collections:
  details:
    output: true