title: Civic Technology
description: >
  University of Chicago Computational Analytics and Public Policy
baseurl: "/civictechcourse"
url: "https://abhinemani.com"
paginate:	2 # The number of posts to show per page on your homepage
name: "Abhi Nemani"
email: abhinemani@uchicago.edu
markdown: kramdown
logo: /assets/images/square.jpg
permalink: none
kramdown:
  parse_block_html: true
plugins:
  - jekyll-paginate
collections:
  details:
    output: true